- hosts: linux
  become: yes
  tasks:
  - name: create fact directory
    file:
      path=facts.d
      recurse=yes
      state=directory
  - name: copy fact script to fact directory
    template:
      src=datetime.sh.j2
      dest=facts.d/date_time.fact
      mode=0755
  - name: reload ansible fact
    setup: filter=ansible_local
  - name: print local fact
    debug:
      msg: " custom fact is {{ ansible_local.date_time }}"
